version: '3.8'

services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  web:
    image: thongchau/mid-devops-nodejs:latest
    container_name: node-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/midterm-devops
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
